name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{ secrets.DOCKERHUB_ENV }}" > .env
      - name: Build the Docker image
        run: docker build --progress=plain -t huyduongdn/mkt-login-app:v0 .
      - name: Login in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push huyduongdn/mkt-login-app:v0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: linuxserver.io
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull huyduongdn/mkt-login-app:v0
            docker stop mkt-login-app
            docker rm mkt-login-app
            docker run -dp 3000:3000 --name mkt-login-app --restart unless-stopped huyduongdn/mkt-login-app:v0
