name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: echo "${{ secrets.DOCKERHUB_ENV }}" > .env
      - name: Build the Docker image
        run: docker build --progress=plain -t huyduongdn/mkt-login-app:v0 .
      - name: Login in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push the Docker image
        run: docker push huyduongdn/mkt-login-app:v0
